TALENT_POOL: list[dict] = [
    {
        "name": "Ananya Rao",
        "title": "Senior Backend Engineer",
        "company": "Razorpay",
        "location": "Bengaluru",
        "headline": "Builds payment ledgers and high-throughput APIs in Python and Go",
        "skills": ["python", "fastapi", "postgresql", "redis", "kafka", "go", "aws"],
        "email": "ananya.rao@example.com",
        "profile_url": "https://linkedin.com/in/example-ananya-rao",
    },
    {
        "name": "Rohit Menon",
        "title": "Staff Frontend Engineer",
        "company": "Swiggy",
        "location": "Bengaluru",
        "headline": "Design systems and React performance for consumer apps",
        "skills": ["react", "typescript", "next.js", "css", "graphql", "playwright"],
        "email": "rohit.menon@example.com",
        "profile_url": "https://linkedin.com/in/example-rohit-menon",
    },
    {
        "name": "Meera Iyer",
        "title": "Machine Learning Engineer",
        "company": "Flipkart",
        "location": "Bengaluru",
        "headline": "Ranking models and LLM evaluation for search relevance",
        "skills": ["python", "pytorch", "llm", "nlp", "spark", "airflow"],
        "email": "meera.iyer@example.com",
        "profile_url": "https://linkedin.com/in/example-meera-iyer",
    },
    {
        "name": "Arjun Patel",
        "title": "Full Stack Engineer",
        "company": "Freshworks",
        "location": "Chennai",
        "headline": "TypeScript and Python services for B2B SaaS workflows",
        "skills": ["typescript", "react", "node.js", "python", "postgres", "docker"],
        "email": "arjun.patel@example.com",
        "profile_url": "https://linkedin.com/in/example-arjun-patel",
    },
    {
        "name": "Sana Qureshi",
        "title": "Product Manager",
        "company": "CRED",
        "location": "Bengaluru",
        "headline": "0-to-1 fintech products with strong growth loops",
        "skills": ["product", "roadmapping", "sql", "analytics", "fintech"],
        "email": "sana.qureshi@example.com",
        "profile_url": "https://linkedin.com/in/example-sana-qureshi",
    },
    {
        "name": "Vikram Shah",
        "title": "DevOps Engineer",
        "company": "PhonePe",
        "location": "Pune",
        "headline": "Kubernetes platforms, observability, and incident response",
        "skills": ["kubernetes", "terraform", "aws", "prometheus", "ci/cd", "linux"],
        "email": "vikram.shah@example.com",
        "profile_url": "https://linkedin.com/in/example-vikram-shah",
    },
    {
        "name": "Nisha Kulkarni",
        "title": "Data Engineer",
        "company": "Jio",
        "location": "Mumbai",
        "headline": "Warehouse modeling and streaming pipelines at scale",
        "skills": ["spark", "airflow", "sql", "dbt", "kafka", "python", "bigquery"],
        "email": "nisha.kulkarni@example.com",
        "profile_url": "https://linkedin.com/in/example-nisha-kulkarni",
    },
    {
        "name": "Farhan Ali",
        "title": "Android Engineer",
        "company": "ShareChat",
        "location": "Bengaluru",
        "headline": "Kotlin apps with offline-first sync and performance budgets",
        "skills": ["kotlin", "android", "jetpack", "java", "firebase"],
        "email": "farhan.ali@example.com",
        "profile_url": "https://linkedin.com/in/example-farhan-ali",
    },
    {
        "name": "Priya Nair",
        "title": "People Operations Lead",
        "company": "Zoho",
        "location": "Hyderabad",
        "headline": "High-volume hiring ops, onboarding, and HR analytics",
        "skills": ["hr", "recruiting", "onboarding", "excel", "workday"],
        "email": "priya.nair@example.com",
        "profile_url": "https://linkedin.com/in/example-priya-nair",
    },
    {
        "name": "Karthik Reddy",
        "title": "Account Executive",
        "company": "Freshworks",
        "location": "Hyderabad",
        "headline": "Mid-market SaaS sales with consultative discovery",
        "skills": ["sales", "saas", "negotiation", "crm", "apollo"],
        "email": "karthik.reddy@example.com",
        "profile_url": "https://linkedin.com/in/example-karthik-reddy",
    },
    {
        "name": "Ishita Bose",
        "title": "UX Designer",
        "company": "Meesho",
        "location": "Bengaluru",
        "headline": "Research-backed product design for vernacular commerce",
        "skills": ["figma", "research", "prototyping", "design systems"],
        "email": "ishita.bose@example.com",
        "profile_url": "https://linkedin.com/in/example-ishita-bose",
    },
    {
        "name": "Aditya Verma",
        "title": "Platform Engineer",
        "company": "Atlassian",
        "location": "Bengaluru",
        "headline": "Internal developer platforms and golden paths",
        "skills": ["golang", "kubernetes", "python", "grpc", "aws"],
        "email": "aditya.verma@example.com",
        "profile_url": "https://linkedin.com/in/example-aditya-verma",
    },
    {
        "name": "Lakshmi Subramanian",
        "title": "QA Automation Engineer",
        "company": "Thoughtworks",
        "location": "Chennai",
        "headline": "End-to-end test strategy for distributed services",
        "skills": ["playwright", "cypress", "python", "ci/cd", "api testing"],
        "email": "lakshmi.subramanian@example.com",
        "profile_url": "https://linkedin.com/in/example-lakshmi-subramanian",
    },
    {
        "name": "Mohammed Irfan",
        "title": "iOS Engineer",
        "company": "Dream11",
        "location": "Mumbai",
        "headline": "SwiftUI features with strong accessibility and analytics",
        "skills": ["swift", "ios", "swiftui", "combine"],
        "email": "mohammed.irfan@example.com",
        "profile_url": "https://linkedin.com/in/example-mohammed-irfan",
    },
    {
        "name": "Divya Sharma",
        "title": "Recruiter",
        "company": "Google",
        "location": "Hyderabad",
        "headline": "Technical recruiting for backend and data roles in India",
        "skills": ["recruiting", "sourcing", "boolean search", "stakeholder management"],
        "email": "divya.sharma@example.com",
        "profile_url": "https://linkedin.com/in/example-divya-sharma",
    },
    {
        "name": "Siddharth Jain",
        "title": "Data Scientist",
        "company": "Amazon",
        "location": "Hyderabad",
        "headline": "Causal inference and forecasting for retail demand",
        "skills": ["python", "sql", "statistics", "pandas", "sagemaker"],
        "email": "siddharth.jain@example.com",
        "profile_url": "https://linkedin.com/in/example-siddharth-jain",
    },
    {
        "name": "Pooja Desai",
        "title": "Customer Success Manager",
        "company": "Postman",
        "location": "Pune",
        "headline": "Expansion and retention for developer-tool accounts",
        "skills": ["customer success", "saas", "onboarding", "sql"],
        "email": "pooja.desai@example.com",
        "profile_url": "https://linkedin.com/in/example-pooja-desai",
    },
    {
        "name": "Nikhil Gupta",
        "title": "Security Engineer",
        "company": "CRED",
        "location": "Bengaluru",
        "headline": "Application security, threat modeling, and detection",
        "skills": ["security", "python", "aws", "siem", "appsec"],
        "email": "nikhil.gupta@example.com",
        "profile_url": "https://linkedin.com/in/example-nikhil-gupta",
    },
    {
        "name": "Aisha Khan",
        "title": "HR Business Partner",
        "company": "Unilever",
        "location": "Mumbai",
        "headline": "Plant and field workforce HR for 40+ locations",
        "skills": ["hrbp", "industrial relations", "attendance", "payroll"],
        "email": "aisha.khan@example.com",
        "profile_url": "https://linkedin.com/in/example-aisha-khan",
    },
    {
        "name": "Rahul Chatterjee",
        "title": "Site Reliability Engineer",
        "company": "LinkedIn",
        "location": "Bengaluru",
        "headline": "SLO practice and chaos testing for member graph services",
        "skills": ["sre", "kubernetes", "golang", "observability", "python"],
        "email": "rahul.chatterjee@example.com",
        "profile_url": "https://linkedin.com/in/example-rahul-chatterjee",
    },
    {
        "name": "Tanvi Kapoor",
        "title": "Growth Marketer",
        "company": "Nykaa",
        "location": "Gurugram",
        "headline": "Performance marketing and lifecycle campaigns",
        "skills": ["growth", "seo", "paid ads", "analytics", "sql"],
        "email": "tanvi.kapoor@example.com",
        "profile_url": "https://linkedin.com/in/example-tanvi-kapoor",
    },
    {
        "name": "Harsh Vardhan",
        "title": "React Native Engineer",
        "company": "CRED",
        "location": "Bengaluru",
        "headline": "Cross-platform mobile with native bridges",
        "skills": ["react native", "typescript", "ios", "android"],
        "email": "harsh.vardhan@example.com",
        "profile_url": "https://linkedin.com/in/example-harsh-vardhan",
    },
    {
        "name": "Shreya Banerjee",
        "title": "Talent Acquisition Specialist",
        "company": "Microsoft",
        "location": "Hyderabad",
        "headline": "High-volume campus and lateral hiring for cloud roles",
        "skills": ["recruiting", "campus", "ats", "stakeholder management"],
        "email": "shreya.banerjee@example.com",
        "profile_url": "https://linkedin.com/in/example-shreya-banerjee",
    },
    {
        "name": "Manish Tiwari",
        "title": "Field Sales Manager",
        "company": "Byju's",
        "location": "Lucknow",
        "headline": "Multi-city field teams and territory planning",
        "skills": ["field sales", "team management", "crm", "negotiation"],
        "email": "manish.tiwari@example.com",
        "profile_url": "https://linkedin.com/in/example-manish-tiwari",
    },
    {
        "name": "Kavya Krishnan",
        "title": "NLP Engineer",
        "company": "Sarvam AI",
        "location": "Bengaluru",
        "headline": "Indic language models and speech pipelines",
        "skills": ["nlp", "llm", "python", "speech", "pytorch", "hindi"],
        "email": "kavya.krishnan@example.com",
        "profile_url": "https://linkedin.com/in/example-kavya-krishnan",
    },
    {
        "name": "Jose Dsouza",
        "title": "Operations Manager",
        "company": "Delhivery",
        "location": "Delhi",
        "headline": "Hub operations, shift planning, and attendance discipline",
        "skills": ["operations", "logistics", "excel", "workforce"],
        "email": "jose.dsouza@example.com",
        "profile_url": "https://linkedin.com/in/example-jose-dsouza",
    },
    {
        "name": "Ritika Malhotra",
        "title": "Backend Engineer",
        "company": "Zerodha",
        "location": "Bengaluru",
        "headline": "Low-latency trading APIs in Python and Rust",
        "skills": ["python", "rust", "redis", "postgresql", "systems"],
        "email": "ritika.malhotra@example.com",
        "profile_url": "https://linkedin.com/in/example-ritika-malhotra",
    },
    {
        "name": "Aman Singh",
        "title": "Solution Architect",
        "company": "Infosys",
        "location": "Pune",
        "headline": "Enterprise integrations and cloud migration programs",
        "skills": ["architecture", "java", "aws", "microservices", "kafka"],
        "email": "aman.singh@example.com",
        "profile_url": "https://linkedin.com/in/example-aman-singh",
    },
    {
        "name": "Neelam Joshi",
        "title": "Payroll Specialist",
        "company": "KPMG",
        "location": "Gurugram",
        "headline": "Multi-state payroll, PF/ESI, and attendance recon",
        "skills": ["payroll", "compliance", "excel", "hris"],
        "email": "neelam.joshi@example.com",
        "profile_url": "https://linkedin.com/in/example-neelam-joshi",
    },
    {
        "name": "Gaurav Bhatt",
        "title": "Voice AI Engineer",
        "company": "Hunar.ai",
        "location": "Remote",
        "headline": "Telephony, ASR, and agent orchestration for HR workflows",
        "skills": ["voice ai", "python", "twilio", "llm", "telephony"],
        "email": "gaurav.bhatt@example.com",
        "profile_url": "https://linkedin.com/in/example-gaurav-bhatt",
    },
    {
        "name": "Sneha Pillai",
        "title": "Business Analyst",
        "company": "TCS",
        "location": "Kochi",
        "headline": "Requirements, process maps, and UAT for HR systems",
        "skills": ["analysis", "sql", "jira", "hris", "documentation"],
        "email": "sneha.pillai@example.com",
        "profile_url": "https://linkedin.com/in/example-sneha-pillai",
    },
    {
        "name": "Yusuf Rahman",
        "title": "Node.js Engineer",
        "company": "BrowserStack",
        "location": "Mumbai",
        "headline": "Realtime services and developer tooling APIs",
        "skills": ["node.js", "typescript", "redis", "postgresql", "websockets"],
        "email": "yusuf.rahman@example.com",
        "profile_url": "https://linkedin.com/in/example-yusuf-rahman",
    },
]
